POST https://localhost:7279/users
Content-Type: application/json

{
    "userName": "hungpham",
    "name": "Phạm Thành Hưng",
    "role": "User",
    "password": "12345678",
    "phoneNumber": "0971169255",
    "active": true,
    "activeTimeStart": "2023-01-31T16:33:21",
  "activeTimeEnd": "2023-05-30T00:00:00"
}