POST https://localhost:7279/users
Content-Type: application/json

{
    "userName": "hungpham13",
    "name": "Phạm Thành Hưng",
    "role": "Admin",
    "password": "123456",
    "phoneNumber": "0971169255"
}