POST https://localhost:7279/users
Content-Type: application/json

{
    "userName": "hung0",
    "name": "Phạm Thành Hưng",
    "role": "User",
    "password": "12345678",
    "phoneNumber": "0971169255",
    "active": false
}