GET https://localhost:7279/users?page=1&size=0&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NmM4OWFhMS03MDQ1LTQ4ZmEtYWM2OS00ODIwOTgwZWVlMTIiLCJ1bmlxdWVfbmFtZSI6Imh1bmdwaGFtIiwidHlwIjoiVXNlciIsImp0aSI6IjY5OWRhYTQyLWQyMzktNDZjYi1hNTNlLTQyZTFmMDQ0ZmY5MCIsImV4cCI6MTY3NTE1NzM3MSwiaXNzIjoiVGVzdERvdG5ldEFQSSJ9.7SZp_HOFjW37eihKYAfUWnBnS2l6ISwBVk-a36X-bFA